# Generated by Django 5.1 on 2024-08-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('Add', 'can_create'), ('View', 'can_view'), ('Edit', 'can_edit'), ('Delete', 'can_delete')]},
        ),
    ]
