# Generated by Django 5.1 on 2024-08-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publication_year',
        ),
    ]
