# Generated by Django 5.1 on 2024-08-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('Add Book', 'can_add_book'), ('Change Book', 'can_cahnge_book'), ('Edit Books', 'can_delete_book')]},
        ),
    ]
