# Generated by Django 5.1 on 2024-08-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('Add Book', 'can_add_book'), ('Edit Book', 'can_change_book'), ('Delete Books', 'can_delete_book')]},
        ),
    ]
